@host = http://localhost:5000/api/v1/users

GET {{host}}
###
GET {{host}}/rut
###
GET {{host}}/status HTTP/1.1

###
POST {{host}}/newRouteData
content-type: application/json

{
    
    "origen": "Montería, Córdoba",
    "destino": "Medellín, Antioquia",
    "valorPorKm": {
        "$numberInt": "3500"
    },
    "distanciaKm": {
        "$numberInt": "401"
    },
    "valorRuta": {
        "$numberInt": "1400000"
    },
    "status": "🟢"
}